name: Print current date

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print date
      run: echo "Current date: $(date +"%A, %B %d, %Y %H:%M:%S")"
